### ISSUE TITLE
Error video no play

### ISSUE THREAD

**Issue by ghost** [WangYng/better_video_player#1]
```
D/NativeCrypto(28749):  sslNotify, appData=0x9888f340 ret=1
D/NativeCrypto(28749): ssl=0x8b67a840 info_callback where=0x4008 ret=256
D/NativeCrypto(28749): ssl=0x8b67a840 SSL3 alert write:W:CN warning close notify
D/NativeCrypto(28749): ssl=0x8b67a840 info_callback ignored
I/System.out(28749): Close in OkHttp
I/System.out(28749): close [socket][/192.168.0.100:33900]
E/flutter (28749): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error, null, null)
```

Link test "https://assets.mixkit.co/videos/preview/mixkit-woman-on-a-video-call-in-outdoors-39813-large.mp4"

**Comment by WangYng** [comment]
Can you provide more detailed information?

**Comment by ghost** [comment]
> Can you provide more detailed information?

I try to run this link in the video player and it doesn't work.

```dart
BetterPlayer.network(
          "https://assets.mixkit.co/videos/preview/mixkit-woman-on-a-video-call-in-outdoors-39813-large.mp4",
          betterPlayerConfiguration: BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
          ),
```

**Comment by matheusqro** [comment]
> > Can you provide more detailed information?
> 
> I try to rotate this link in the video player and it doesn't work.
> 
> ```dart
> BetterPlayer.network(
>           "https://assets.mixkit.co/videos/preview/mixkit-woman-on-a-video-call-in-outdoors-39813-large.mp4",
>           betterPlayerConfiguration: BetterPlayerConfiguration(
>             aspectRatio: 16 / 9,
>           ),
> ```

**Comment by matheusqro** [comment]
Sorry!

**Comment by WangYng** [comment]
This library is not [BetterPlayer](https://github.com/jhomlala/betterplayer).
